service: ciprisma
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  environment: ${file(configs.js)}

custom:
  dotenvVars: ${file(configs.js)}
  webpack:
    includeModules: true
  prisma:
    #define prisma schema path
    # prismaPath: "./src"
  serverless-offline:
    httpPort: 4000

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-offline

functions:
  api:
    handler: src/handler.server
    events:
      - httpApi: "*"
